using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class SoundManager : MonoBehaviour
{
    public static SoundManager Instance = null;
    private AudioSource soundEffectAudio;
    public AudioClip scanObjectBeep;
    public AudioClip footsteps;
    public AudioClip cartWheels;
    public AudioClip cartStop;
    public AudioClip storeDoors;

    // Use this for initialization
    void Start()
    {
        if (Instance == null)
        {
            Instance = this;
        }
        else if (Instance != this)
        {
            Destroy(gameObject);
        }
        AudioSource[] sources = GetComponents<AudioSource>();
        foreach (AudioSource source in sources)
        {
            if (source.clip == null)
            {
                soundEffectAudio = source;
            }
        }
    }

    void Update()
    {
    }

    public void PlayOneShot(AudioClip clip)
    {
        soundEffectAudio.PlayOneShot(clip);
    }

    //This is what you put in the place you want the sound to happen
    
    //SoundManager.Instance.PlayOneShot(SoundManager.Instance.scanObjectBeep);
}